[enderman_farm]
	#The time in ticks the enderman farm takes to spawn an enderman
	#Range: 180 ~ 180
	spawn_time = 180

[spider_farm]
	#The time in ticks the spider farm takes to spawn a spider
	#Range: 60 ~ 60
	spawn_time = 60

[villager]
	#If the villager reputation should be the same for every player
	#This affects the prices of cured/converted villagers and the prices of the auto trader
	universal_reputation = true
